const KEY="miProgresoDataV3",OLD=["miProgresoDataV2","miProgresoDataV1"],FOODS=[{"name": "Pan blanco", "unit": "rebanada 30 g", "calories": 80, "protein": 2.5, "carbs": 15, "fat": 1}, {"name": "Jamón de pavo", "unit": "30 g", "calories": 35, "protein": 6, "carbs": 1, "fat": 1}, {"name": "Queso fresco", "unit": "30 g", "calories": 80, "protein": 5, "carbs": 1, "fat": 6}, {"name": "Huevo cocido", "unit": "unidad", "calories": 78, "protein": 6.3, "carbs": 0.6, "fat": 5.3}, {"name": "Pechuga de pollo", "unit": "100 g", "calories": 165, "protein": 31, "carbs": 0, "fat": 3.6}, {"name": "Arroz cocido", "unit": "100 g", "calories": 130, "protein": 2.7, "carbs": 28, "fat": 0.3}, {"name": "Papa cocida", "unit": "100 g", "calories": 87, "protein": 1.9, "carbs": 20, "fat": 0.1}, {"name": "Aguacate", "unit": "100 g", "calories": 160, "protein": 2, "carbs": 8.5, "fat": 14.7}, {"name": "Yogurt natural", "unit": "100 ml", "calories": 63, "protein": 3.5, "carbs": 4.7, "fat": 3.3}, {"name": "Manzana roja", "unit": "100 g", "calories": 52, "protein": 0.3, "carbs": 14, "fat": 0.2}, {"name": "Kiwi", "unit": "100 g", "calories": 61, "protein": 1.1, "carbs": 15, "fat": 0.5}, {"name": "Frutos rojos congelados", "unit": "100 g", "calories": 50, "protein": 1, "carbs": 12, "fat": 0.4}, {"name": "Atún en agua", "unit": "100 g", "calories": 116, "protein": 26, "carbs": 0, "fat": 1}, {"name": "Camarón cocido", "unit": "100 g", "calories": 99, "protein": 24, "carbs": 0.2, "fat": 0.3}, {"name": "Avena", "unit": "40 g", "calories": 152, "protein": 5.2, "carbs": 27, "fat": 2.8}, {"name": "Café sin azúcar", "unit": "taza", "calories": 2, "protein": 0.3, "carbs": 0, "fat": 0}, {"name": "Ensalada mixta", "unit": "200 g", "calories": 70, "protein": 3, "carbs": 14, "fat": 0.7}, {"name": "Bolón mixto", "unit": "200 g", "calories": 550, "protein": 18, "carbs": 65, "fat": 25}, {"name": "Ceviche de camarón", "unit": "porción", "calories": 250, "protein": 28, "carbs": 20, "fat": 6}];
const DEF={profile:{name:"",height:"",goalWeight:"",calorieGoal:2000,proteinGoal:100,waterGoal:2000,activityGoal:30},foods:[],weights:[],doses:[],symptoms:[],water:[],activities:[],theme:"light"};
let data=load();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],today=()=>new Date().toISOString().slice(0,10),uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function load(){try{let raw=localStorage.getItem(KEY);if(!raw)for(const k of OLD)if(localStorage.getItem(k)){raw=localStorage.getItem(k);break}const d=raw?JSON.parse(raw):{};return {...structuredClone(DEF),...d,profile:{...DEF.profile,...(d.profile||{})},water:d.water||[],activities:d.activities||[]}}catch{return structuredClone(DEF)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function fmtDate(d){return new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short"}).format(new Date(d+"T12:00:00"))}
function fmtDT(d){return new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(d))}
document.addEventListener("DOMContentLoaded",()=>{$("#todayLabel").textContent=new Intl.DateTimeFormat("es-EC",{weekday:"long",day:"numeric",month:"long"}).format(new Date());$("#foodDateFilter").value=today();dates();bind();renderAll();if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js")}); 
function dates(){$$('input[type="date"]').forEach(i=>{if(!i.value)i.value=today()});const x=$('input[type="datetime-local"]');if(x&&!x.value){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());x.value=d.toISOString().slice(0,16)}}
function bind(){
 $$(".nav-item").forEach(b=>b.onclick=()=>show(b.dataset.view));$$("[data-open]").forEach(b=>b.onclick=()=>openM(b.dataset.open));$$(".close-modal").forEach(b=>b.onclick=closeM);$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)closeM()});
 $("#themeToggle").onclick=()=>{data.theme=data.theme==="dark"?"light":"dark";save()};
 $("#foodDateFilter").onchange=renderFood;$("#foodSearch").oninput=searchFood;
 $("#foodForm").onsubmit=saveFood;$("#weightForm").onsubmit=e=>simple(e,"weights",o=>({...o,id:uid(),weight:+o.weight,waist:+o.waist||null}));$("#doseForm").onsubmit=e=>simple(e,"doses",o=>({...o,id:uid(),dose:+o.dose}));$("#symptomForm").onsubmit=e=>simple(e,"symptoms",o=>({...o,id:uid()}));$("#waterForm").onsubmit=e=>simple(e,"water",o=>({...o,id:uid(),ml:+o.ml}));$("#activityForm").onsubmit=e=>simple(e,"activities",o=>({...o,id:uid(),minutes:+o.minutes}));
 $$("[data-water]").forEach(b=>b.onclick=()=>$('#waterForm [name="ml"]').value=b.dataset.water);
 $("#profileForm").onsubmit=profile;$("#settingsForm").onsubmit=e=>{e.preventDefault();data.profile.calorieGoal=+new FormData(e.target).get("calorieGoal");save();closeM()};
 $("#exportBackup").onclick=backup;$("#importBackup").onchange=restore;$("#exportCsv").onclick=csv;$("#clearData").onclick=clearAll;$("#printReportBtn").onclick=report;$("#printReportBtn2").onclick=report;
}
function show(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id));scrollTo(0,0);renderAll()}
function openM(id){$("#"+id).classList.add("open");if(id==="profileModal")Object.keys(DEF.profile).forEach(k=>{const x=$(`#profileForm [name="${k}"]`);if(x)x.value=data.profile[k]||""});if(id==="settingsModal")$('#settingsForm [name="calorieGoal"]').value=data.profile.calorieGoal;dates()}
function closeM(){$$(".modal").forEach(m=>m.classList.remove("open"))}
function simple(e,col,map){e.preventDefault();data[col].push(map(Object.fromEntries(new FormData(e.target))));e.target.reset();save();closeM();dates()}
async function saveFood(e){e.preventDefault();const f=new FormData(e.target),o=Object.fromEntries(f),file=f.get("photo");o.id=uid();["calories","protein","carbs","fat"].forEach(k=>o[k]=+o[k]||0);if(file&&file.size)o.photo=await shrink(file);else delete o.photo;data.foods.push(o);e.target.reset();save();closeM();dates()}
function shrink(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{let w=im.width,h=im.height,s=Math.min(1,600/Math.max(w,h));const c=document.createElement("canvas");c.width=w*s;c.height=h*s;c.getContext("2d").drawImage(im,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.72))};im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
function profile(e){e.preventDefault();const o=Object.fromEntries(new FormData(e.target));["height","goalWeight","proteinGoal","waterGoal","activityGoal"].forEach(k=>o[k]=+o[k]||DEF.profile[k]);data.profile={...data.profile,...o};save();closeM()}
function searchFood(){const q=$("#foodSearch").value.toLowerCase().trim(),box=$("#foodSuggestions");if(q.length<2){box.innerHTML="";return}box.innerHTML=FOODS.filter(x=>x.name.toLowerCase().includes(q)).slice(0,6).map(x=>`<button type="button" class="suggestion" data-name="${esc(x.name)}"><b>${x.name}</b><br><small>${x.calories} kcal · ${x.unit}</small></button>`).join("");$$(".suggestion").forEach(b=>b.onclick=()=>{const x=FOODS.find(f=>f.name===b.dataset.name),f=$("#foodForm");f.name.value=x.name;f.calories.value=x.calories;f.protein.value=x.protein;f.carbs.value=x.carbs;f.fat.value=x.fat;box.innerHTML=""})}
function day(col,d=today()){return data[col].filter(x=>(x.date||x.datetime?.slice(0,10))===d)}function sum(a,k){return a.reduce((s,x)=>s+(+x[k]||0),0)}function weights(){return [...data.weights].sort((a,b)=>a.date.localeCompare(b.date))}function doses(){return [...data.doses].sort((a,b)=>a.datetime.localeCompare(b.datetime))}
function renderAll(){document.documentElement.dataset.theme=data.theme||"light";renderHome();renderFood();renderWeight();renderDose();renderHealth()}
function renderHome(){const f=day("foods"),cal=sum(f,"calories"),g=data.profile.calorieGoal,pct=Math.min(100,cal/g*100||0);$("#caloriesConsumed").textContent=Math.round(cal);$("#calorieGoal").textContent=g;$("#caloriesRemaining").textContent=Math.max(0,g-cal);$("#calorieBar").style.width=pct+"%";$("#calorieRing").style.background=`conic-gradient(#fff ${pct*3.6}deg,rgba(255,255,255,.25) 0)`;$("#streakDays").textContent=streak();const w=weights(),cur=w.at(-1),first=w[0];$("#currentWeight").textContent=cur?cur.weight.toFixed(1)+" kg":"—";$("#weightDelta").textContent=cur&&first?`${cur.weight-first.weight<=0?"↓":"↑"} ${Math.abs(cur.weight-first.weight).toFixed(1)} kg desde inicio`:"Sin registros";const d=doses(),last=d.at(-1);if(last){const n=new Date(last.datetime);n.setDate(n.getDate()+7);$("#nextDoseDate").textContent=fmtDate(n.toISOString().slice(0,10));$("#lastDoseText").textContent=`Última: ${last.dose} mg`}else{$("#nextDoseDate").textContent="—";$("#lastDoseText").textContent="Sin aplicaciones"}drawLine($("#weightChart"),w.slice(-7));achievements()}
function streak(){const dates=new Set(["foods","weights","doses","symptoms","water","activities"].flatMap(k=>data[k].map(x=>x.date||x.datetime.slice(0,10))));let n=0,d=new Date();while(dates.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function achievements(){const w=weights(),lost=w.length>1?w[0].weight-w.at(-1).weight:0,items=[["🔥","Primer registro",total()>0],["⚖️","Primer peso",w.length>0],["💉","Primera dosis",data.doses.length>0],["🏅","1 kg menos",lost>=1],["🏆","5 kg menos",lost>=5],["📆","Racha de 7 días",streak()>=7]];$("#achievements").innerHTML=items.map(([i,t,u])=>`<div class="achievement ${u?"unlocked":""}"><span>${i}</span><div><b>${t}</b><small>${u?"Desbloqueado":"Pendiente"}</small></div></div>`).join("")}function total(){return ["foods","weights","doses","symptoms","water","activities"].reduce((s,k)=>s+data[k].length,0)}
function renderFood(){const d=$("#foodDateFilter")?.value||today(),a=day("foods",d);$("#foodSummary").innerHTML=[["kcal",Math.round(sum(a,"calories"))],["Proteína",Math.round(sum(a,"protein"))+" g"],["Carbos",Math.round(sum(a,"carbs"))+" g"],["Grasa",Math.round(sum(a,"fat"))+" g"]].map(x=>`<div class="macro"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join("");$("#foodList").innerHTML=a.length?a.map(x=>`<div class="list-item"><div>${x.photo?`<img class="food-thumb" src="${x.photo}">`:""}<h4>${esc(x.name)}</h4><p>${x.meal} · P ${x.protein||0} g</p></div><div><strong>${x.calories} kcal</strong><button class="delete-btn" onclick="removeItem('foods','${x.id}')">×</button></div></div>`).join(""):'<div class="empty">No hay comidas registradas.</div>'}
function renderWeight(){const w=weights(),a=[...w].reverse(),cur=w.at(-1),first=w[0],goal=+data.profile.goalWeight||0;$("#goalWeightLabel").textContent=goal?goal.toFixed(1)+" kg":"—";$("#goalProgressLabel").textContent=goal&&cur?Math.max(0,cur.weight-goal).toFixed(1)+" kg por perder":"Configúrala";$("#totalLost").textContent=cur&&first?(first.weight-cur.weight).toFixed(1)+" kg":"—";drawLine($("#fullWeightChart"),w);$("#weightList").innerHTML=a.length?a.map(x=>`<div class="list-item"><div><h4>${fmtDate(x.date)}</h4><p>${x.waist?`Cintura ${x.waist} cm`:""}</p></div><div><strong>${x.weight.toFixed(1)} kg</strong><button class="delete-btn" onclick="removeItem('weights','${x.id}')">×</button></div></div>`).join(""):'<div class="empty">Aún no hay pesos.</div>'}
function renderDose(){const a=[...doses()].reverse();$("#doseList").innerHTML=a.length?a.map(x=>`<div class="list-item"><div><h4>${x.dose} mg</h4><p>${fmtDT(x.datetime)} · ${esc(x.site)}</p></div><button class="delete-btn" onclick="removeItem('doses','${x.id}')">×</button></div>`).join(""):'<div class="empty">Aún no hay aplicaciones.</div>'}
function renderHealth(){const w=sum(day("water"),"ml"),a=sum(day("activities"),"minutes"),s=day("symptoms");$("#waterTodayText").textContent=`${w} ml hoy`;$("#activityTodayText").textContent=`${a} min hoy`;$("#symptomTodayText").textContent=s.length?`${s.length} registro(s) hoy`:"Sin síntomas hoy";const arr=[...data.symptoms].sort((x,y)=>y.date.localeCompare(x.date)).slice(0,12);$("#symptomList").innerHTML=arr.length?arr.map(x=>`<div class="list-item"><div><h4>${esc(x.symptom)} · ${esc(x.severity)}</h4><p>${fmtDate(x.date)} · ${esc(x.notes||"")}</p></div><button class="delete-btn" onclick="removeItem('symptoms','${x.id}')">×</button></div>`).join(""):'<div class="empty">No hay síntomas registrados.</div>'}
window.removeItem=(c,id)=>{if(confirm("¿Eliminar este registro?")){data[c]=data[c].filter(x=>x.id!==id);save()}}
function drawLine(c,a){
 if(!c)return;
 const ctx=c.getContext("2d");
 const dpr=window.devicePixelRatio||1;
 const w=Math.max(280,c.clientWidth||300);
 const baseHeight=Number(c.dataset.baseHeight||c.getAttribute("height")||180);
 c.dataset.baseHeight=baseHeight;
 c.style.height=baseHeight+"px";
 c.width=Math.round(w*dpr);
 c.height=Math.round(baseHeight*dpr);
 ctx.setTransform(dpr,0,0,dpr,0,0);
 ctx.clearRect(0,0,w,baseHeight);
 ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue("--border");
 ctx.lineWidth=1;
 for(let i=1;i<5;i++){
  const y=baseHeight*i/5;
  ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();
 }
 if(a.length<2){
  ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue("--muted");
  ctx.font="13px sans-serif";
  ctx.fillText("Registra al menos dos pesos para ver la gráfica.",12,baseHeight/2);
  return;
 }
 const v=a.map(x=>x.weight),mn=Math.min(...v)-1,mx=Math.max(...v)+1;
 const px=i=>18+i*(w-36)/(a.length-1);
 const py=x=>18+(mx-x)*(baseHeight-36)/(mx-mn);
 ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue("--primary");
 ctx.lineWidth=4;ctx.lineJoin="round";ctx.lineCap="round";
 ctx.beginPath();
 a.forEach((x,i)=>i?ctx.lineTo(px(i),py(x.weight)):ctx.moveTo(px(i),py(x.weight)));
 ctx.stroke();
 ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue("--primary");
 a.forEach((x,i)=>{ctx.beginPath();ctx.arc(px(i),py(x.weight),4,0,Math.PI*2);ctx.fill()});
}
function backup(){download(`mi-progreso-${today()}.json`,JSON.stringify(data),"application/json")}function restore(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result);if(confirm("¿Reemplazar datos actuales?")){data={...structuredClone(DEF),...o,profile:{...DEF.profile,...o.profile}};save()}}catch{alert("Archivo inválido")}};r.readAsText(f)}function csv(){const rows=[["tipo","fecha","detalle","valor"]];data.foods.forEach(x=>rows.push(["comida",x.date,x.name,x.calories+" kcal"]));data.weights.forEach(x=>rows.push(["peso",x.date,"Peso",x.weight+" kg"]));data.doses.forEach(x=>rows.push(["dosis",x.datetime,x.site,x.dose+" mg"]));data.water.forEach(x=>rows.push(["agua",x.date,"Agua",x.ml+" ml"]));data.activities.forEach(x=>rows.push(["actividad",x.date,x.type,x.minutes+" min"]));download(`mi-progreso-${today()}.csv`,"\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv")}
function download(n,c,t){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click()}function clearAll(){if(confirm("¿Borrar todos los datos?")){data=structuredClone(DEF);save()}}
function report(){const w=weights(),last=w.at(-1),first=w[0],d=doses().at(-1),html=`<html><head><title>Informe</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><h1>Informe Mi Progreso</h1><p>${esc(data.profile.name||"Paciente")} · ${new Date().toLocaleDateString("es-EC")}</p><p><b>Peso actual:</b> ${last?last.weight+" kg":"Sin dato"}<br><b>Cambio:</b> ${last&&first?(first.weight-last.weight).toFixed(1)+" kg":"Sin dato"}<br><b>Última dosis:</b> ${d?d.dose+" mg · "+fmtDT(d.datetime):"Sin dato"}</p><h2>Pesos recientes</h2><table>${w.slice(-12).map(x=>`<tr><td>${x.date}</td><td>${x.weight} kg</td><td>${x.waist||"—"}</td></tr>`).join("")}</table><script>window.onload=()=>window.print()<\/script></body></html>`;const x=open("","_blank");x.document.write(html);x.document.close()}
